USE NETCORE;


CREATE TABLE CLIENTE(
	ID INT NOT NULL,
	NOMBRE VARCHAR(250),
	DIRECCION VARCHAR (500),
	TELEFONO VARCHAR (10),
	DPI VARCHAR(13),
	FECHA_CREACION DATETIME,
	E_MAIL VARCHAR(100)
	PRIMARY KEY (ID)
);

